version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests

  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./tests:/locust
    command: -f /locust/locustfile.py --master

  locust-worker:
    image: locustio/locust
    volumes:
      - ./tests:/locust
    command: -f /locust/locustfile.py --worker --master-host locust-master
